workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main' && $CI_COMMIT_MESSAGE =~ /See merge request/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - when: never

variables:
  FF_TIMESTAMPS: true
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build

default:
  image: docker:27.3.1
  services:
    - name: docker:27.3.1-dind
      command: ["--tls=false"]
      variables:
        DOCKER_OPTS: "--insecure-registry=$DOCKERREGISTRY"

before_script:
  - apk add -q git jq

build:
  stage: build
  script:
    - export LATEST=$(jq -r '.latest' VERSION)
    - export VERSION=$(jq -r '.version' VERSION)
    - export BUILDDATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
    - echo $(jq -r '.plugins[] | "\nLABEL io.mpoore.packer-ci.plugin.\(.name)=\"\(.version)\""' PLUGINS) >> Dockerfile
    - echo "Building packer-ci image version $VERSION"
    - docker build . -t packer-ci:$VERSION --platform=linux/amd64 --build-arg VERSION=$VERSION --build-arg ARTIFACTORY_URL=$ARTIFACTORY_URL --build-arg BUILDDATE=$BUILDDATE
    - |
      if [ $CI_COMMIT_REF_NAME == 'main' ]; then
        echo $DOCKERPASS | docker login $DOCKERREGISTRY --username $DOCKERUSER --password-stdin
        docker tag packer-ci:$VERSION $DOCKERTARGET:$VERSION
        docker push $DOCKERTARGET:$VERSION
      fi
    - |
      if [ $LATEST == "true" ] && [ $CI_COMMIT_REF_NAME == 'main' ]; then
        docker tag packer-ci:$VERSION $DOCKERTARGET:latest
        docker push $DOCKERTARGET:latest
      fi
  artifacts:
    paths:
      - Dockerfile
      - PLUGINS
      - VERSION