workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /See merge request/
    - when: always

variables:
  FF_TIMESTAMPS: true
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  KUBERNETES_CPU_REQUEST: "3"
  KUBERNETES_CPU_LIMIT: "5"
  KUBERNETES_MEMORY_REQUEST: "2Gi"
  KUBERNETES_MEMORY_LIMIT: "4Gi"
  KUBERNETES_EPHEMERAL_STORAGE_REQUEST: "512Mi"
  KUBERNETES_EPHEMERAL_STORAGE_LIMIT: "1Gi"
  KUBERNETES_HELPER_CPU_REQUEST: "3"
  KUBERNETES_HELPER_CPU_LIMIT: "5"
  KUBERNETES_HELPER_MEMORY_REQUEST: "2Gi"
  KUBERNETES_HELPER_MEMORY_LIMIT: "4Gi"
  KUBERNETES_HELPER_EPHEMERAL_STORAGE_REQUEST: "512Mi"
  KUBERNETES_HELPER_EPHEMERAL_STORAGE_LIMIT: "1Gi"
  KUBERNETES_SERVICE_CPU_REQUEST: "3"
  KUBERNETES_SERVICE_CPU_LIMIT: "5"
  KUBERNETES_SERVICE_MEMORY_REQUEST: "2Gi"
  KUBERNETES_SERVICE_MEMORY_LIMIT: "4Gi"
  KUBERNETES_SERVICE_EPHEMERAL_STORAGE_REQUEST: "512Mi"
  KUBERNETES_SERVICE_EPHEMERAL_STORAGE_LIMIT: "1Gi"

stages:
  - build

default:
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      command: ["--tls=false"]

before_script:
  - apk add -q git 

build:
  stage: build
  script:
    - export VERSION=$(cat VERSION)
    - echo "Building packer-ci image version $VERSION"
    - docker build . -t packer-ci:$VERSION --platform=linux/amd64 --build-arg VERSION=$VERSION
    - docker tag packer-ci:$VERSION $DOCKERTARGET:$VERSION
    - docker tag packer-ci:$VERSION $DOCKERTARGET:latest
    - echo $DOCKERPASS | docker login $DOCKERREGISTRY --username $DOCKERUSER --password-stdin
    - docker push $DOCKERTARGET:$VERSION