workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /See merge request/
    - when: always

variables:
  FF_TIMESTAMPS: true
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build

default:
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      command: command: ["--tls=false"]

before_script:
  - cat /etc/hosts

build:
  stage: build
  script:
    - docker build . -t packer-ci:$VERSION --platform=linux/amd64 --build-arg VERSION=$VERSION
    - docker tag packer-ci:$VERSION $DOCKERTARGET:$VERSION
    - docker tag packer-ci:$VERSION $DOCKERTARGET:latest
    - echo $DOCKERPASS | docker login $DOCKERREGISTRY -u $DOCKERUSER
    - docker push $DOCKERTARGET:$VERSION