workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /See merge request/
    - when: always

variables:
  FF_TIMESTAMPS: true
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build

default:
  image: docker:27.3.1
  services:
    - name: docker:27.3.1-dind
      command: ["--tls=false"]
      variables:
        DOCKER_OPTS: "--insecure-registry=$DOCKERREGISTRY"

before_script:
  - apk add -q git 

build:
  stage: build
  script:
    - export VERSION=$(cat VERSION)
    - echo "Building packer-ci image version $VERSION"
    - docker build . -t packer-ci:$VERSION --platform=linux/amd64 --build-arg VERSION=$VERSION --build-arg ARTIFACTORY_URL=$ARTIFACTORY_URL
    - docker tag packer-ci:$VERSION $DOCKERTARGET:$VERSION
    - docker tag packer-ci:$VERSION $DOCKERTARGET:latest
    - echo $DOCKERPASS | docker login $DOCKERREGISTRY --username $DOCKERUSER --password-stdin
    - docker push $DOCKERTARGET:$VERSION
    - docker push $DOCKERTARGET:latest